### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by FireStreaker2** [FireStreaker2/SupportBot#1]
# todo
- [x] lockdown commands (#2)
- [x] info commands (#3)
- [x] role commands (#4)
- [x] report commands (#5)
- [x] split context menu commands into it's own directory (#7)
- [x] cleanup code and turn reused code into functions/components (#7)
- [x] finish all unfinished ``// TODO``s (#7)
- [x] help command (#8)
- [x] project readme (#6)
- [ ] website integration (#9)
- [ ] migrate from in-memory storage -> db
